<?php

/**
 * @file
 * Main file for hooks and custom function.
 */

use Drupal\Core\Form\FormStateInterface;
use Drupal\user\UserInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function custom_register_form_user_register_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  $form['address'] = [
    '#type' => 'textfield',
    '#title' => 'Your address',
    '#size' => 60,
    '#description' => ['Enter your location.'],
    '#required' => TRUE,
  ];
  $form['phone'] = [
    '#type' => 'textfield',
    '#title' => 'Phone number',
    '#size' => 60,
    '#description' => ['Enter your valid phone number.'],
    '#required' => TRUE,
  ];
  $form['#validate'][] = '_custom_register_user_register_form_validate';
}

/**
 * Validates user phone number.
 */
function _custom_register_user_register_form_validate(array &$form, FormStateInterface $form_state) {
  if (!preg_match('/^\\+?\\d{1,4}?[-.\\s]?\\(?\\d{1,3}?\\)?[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,4}[-.\\s]?\\d{1,9}$/', $form_state->getValue('phone'))) {
    $form_state->setErrorByName('phone', "The phone number is invalid.");
  }
}

/**
 * Implements hook_entity_presave().
 */
function custom_register_user_presave(UserInterface $user) {
  if ($user->isNew()) {
    $user->addRole('reader');
  }
}
