<?php

/**
 * @file
 * For a Custom Weather Block custom template.
 */

/**
 * Returns theme name and variables.
 */
function custom_weather_module_theme() {
  return [
    'weather_theme' => [
      'variables' => [
        'header' => '',
        'user_location' => '',
        'conditions' => '',
        'icon' => '',
        'statistics' => '',
      ],
    ],
    'statistics_theme' => [
      'variables' => [
        'header' => '',
        'table' => '',
      ],
    ],
  ];
}
