<?php

/**
 * @file
 * Functions to support theming in the custom olivero db theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function custom_olivero_db_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function custom_olivero_db_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function custom_olivero_db_preprocess_node(&$variables) {

}
